### ISSUE TITLE
Frontend > Chore > Mudar o nome da função "configHeader" para "configPage" em todas as páginas que essa função estiver sendo chamada.

### ISSUE THREAD

**Issue by FLuiz22** [codexjr-dev/dashboard-codex-web#140]
# OVERVIEW

- Nas páginas do frontend, existe uma função chamada configHeader que tem a finalidade de configurar a página de acordo com a tela em que o usuário está, configurando tanto a sidebar quanto o header, logo, o nome configHeader não faz jus a verdadeira finalidade desta função por isso ela deve ter seu nome trocado para configPage;

# TASKS

- [ ] Trocar o configHeader no arquivo ProjectList.vue;
- [ ] Trocar o configHeader no arquivo Member.vue;
- [ ] Trocar o configHeader no arquivo Link.vue;
- [ ] Trocar o configHeader no arquivo AllNews.js;
