### ISSUE TITLE
Frontend > Refactor > Mudar icone da Aba e Título da Aplicação.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/dashboard-codex-web#3]
# OVERVIEW 
- As páginas do sistema possuem o ícone padrão da Framework Vue (símbolo de um V verde), no entanto, adicionar um ícone padrão para o sistema pode deixar o projeto bem mais característico.
- Juntamente a essa questão, o sistema também está com o título "Direx dashboard". Isso faz com que o sistema, além de possuir um título muito longo na Aba, restrinja o acesso do ambiente somente as lideranças da EJ (diminuindo a transparência e horizontalidade entre os membros).

# TASK
- [x] Criar/Propor um novo ícone;
- [x] Atualizar o ícone presente nas Abas das páginas do sistema;
- [x] Atualizar o título presente nas Abas das páginas do sistema;

**Comment by ManoMax** [comment]
# COMMENTS

- Criar um sistema de configuração do título e do ícone da página, para os usuários finais, pode ser uma feature interessante para o escalonamento do projeto.

**Comment by ManoMax** [comment]
https://github.com/codexjr-dev/dashboard-codex-web/pull/11
