### ISSUE TITLE
Frontend > Style > Configurar espaçamento (:width) dos el-table-column da Página de Links.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/dashboard-codex-web#74]
# OVERVIEW 
- A Página de Membros possui 5 principais colunas em cada card: `Nome`, `URL`, `Departamentos`, `TAGS` e `Ações`.
- Cada um possui um espaçamento similar, no entanto, alguns precisam ter mais espaço do que outros.
- Sendo assim, configure o espaçamento (:width) das colunas para que `URL`, `Departamentos`, `TAGS` e `Ações` tenham um pouco mais de espaço do que `Nome` (que precisa de um espaçamento um pouco menor para ficar bem compreensível).

# TASK
- [ ] Configure o espaçamento de `Nome` para que o mesmo fique adequadamente visível;
- [ ] Configure o espaçamento de `URL` para que o mesmo fique adequadamente visível;
- [ ] Configure o espaçamento de `Departamentos` para que o mesmo fique adequadamente visível;
- [ ] Configure o espaçamento de `TAGS` para que o mesmo fique adequadamente visível;
- [ ] Configure o espaçamento de `Ações` para que o mesmo fique adequadamente visível;
